services:
  library-automation:
    build:
      context: .
      dockerfile: LibraryAutomation.CLI\Docker\Dockerfile
    container_name: library-automation
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=Production